dsadsadsadsa
package de.greenrobot.testdao;

import com.fasterxml.jackson.annotation.JsonProperty;
import de.greenrobot.testdao.annotation2.CustomConstructorAnnotation;
import de.greenrobot.testdao.annotations.ClassAnnotation;
import de.greenrobot.testdao.annotations.ConstructorAnnotation;
import de.greenrobot.testdao.annotations.FieldAnnotation;
import de.greenrobot.testdao.annotations.SetterGetterAnnotation;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table TEST_USER.
 */
@ClassAnnotation
public class TestUser {

    private Long id;
    @FieldAnnotation
    private String name;
    private Integer age;


    @ConstructorAnnotation
    public TestUser() {
    }

    @CustomConstructorAnnotation( name = "myName", age = 25 )
    public TestUser(Long id) {
        this.id = id;
    }

    public TestUser(Long id, String name, Integer age) {
        this.id = id;
        this.name = name;
        this.age = age;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @SetterGetterAnnotation
    public Integer getAge() {
        return age;
    }

    @SetterGetterAnnotation
    @JsonProperty( "years" )
    public void setAge(Integer age) {
        this.age = age;
    }

}
