<#--

Copyright (C) 2011 Markus Junginger, greenrobot (http://greenrobot.de)     
                                                                           
This file is part of greenDAO Generator.                                   
                                                                           
greenDAO Generator is free software: you can redistribute it and/or modify 
it under the terms of the GNU General Public License as published by       
the Free Software Foundation, either version 3 of the License, or          
(at your option) any later version.                                        
greenDAO Generator is distributed in the hope that it will be useful,      
but WITHOUT ANY WARRANTY; without even the implied warranty of             
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the              
GNU General Public License for more details.                               
                                                                           
You should have received a copy of the GNU General Public License          
along with greenDAO Generator.  If not, see <http://www.gnu.org/licenses/>.

-->
package ${entity.javaPackageDao};

import de.greenrobot.dao.internal.DaoConfig;
import ${schema.defaultJavaPackageDao}.DaoSession;
import ${entity.javaPackage}.${entity.classNameDao};

// THIS CODE IS GENERATED BY greenDAO ON INITIAL SETUP OF USER-SPECIFIED DAO.
// YOU SHOULD CUSTOMIZE THIS CLASS FURTHER ACCORDING TO YOUR NEEDS -- REMOVAL
// OF THESE COMMENTS IS HIGHLY ADVISED ONCE YOU'VE DONE THAT.
/** 
 * User-specified DAO for table ${entity.tableName}.
*/
public class ${entity.classNameUserDao} extends ${entity.classNameDao} {

    public ${entity.classNameUserDao}(DaoConfig config) {
        super(config);
    }
    
    public ${entity.classNameUserDao}(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }
}
