package de.greenrobot.daotest;

import de.greenrobot.daotest.customtype.MyTimestamp;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CUSTOM_TYPE_ENTITY".
 */
public class CustomTypeEntity {

    private Long id;
    private MyTimestamp myCustomTimestamp;

    public CustomTypeEntity() {
    }

    public CustomTypeEntity(Long id) {
        this.id = id;
    }

    public CustomTypeEntity(Long id, MyTimestamp myCustomTimestamp) {
        this.id = id;
        this.myCustomTimestamp = myCustomTimestamp;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public MyTimestamp getMyCustomTimestamp() {
        return myCustomTimestamp;
    }

    public void setMyCustomTimestamp(MyTimestamp myCustomTimestamp) {
        this.myCustomTimestamp = myCustomTimestamp;
    }

}
