package de.greenrobot.daotest;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ABCDEF_ENTITY.
 */
public class AbcdefEntity {

    private Long id;
    private Integer a;
    private Integer b;
    private Integer c;
    private Integer d;
    private Integer e;
    private Integer f;
    private Integer g;
    private Integer h;
    private Integer j;
    private Integer i;
    private Integer k;

    public AbcdefEntity() {
    }

    public AbcdefEntity(Long id) {
        this.id = id;
    }

    public AbcdefEntity(Long id, Integer a, Integer b, Integer c, Integer d, Integer e, Integer f, Integer g, Integer h, Integer j, Integer i, Integer k) {
        this.id = id;
        this.a = a;
        this.b = b;
        this.c = c;
        this.d = d;
        this.e = e;
        this.f = f;
        this.g = g;
        this.h = h;
        this.j = j;
        this.i = i;
        this.k = k;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getA() {
        return a;
    }

    public void setA(Integer a) {
        this.a = a;
    }

    public Integer getB() {
        return b;
    }

    public void setB(Integer b) {
        this.b = b;
    }

    public Integer getC() {
        return c;
    }

    public void setC(Integer c) {
        this.c = c;
    }

    public Integer getD() {
        return d;
    }

    public void setD(Integer d) {
        this.d = d;
    }

    public Integer getE() {
        return e;
    }

    public void setE(Integer e) {
        this.e = e;
    }

    public Integer getF() {
        return f;
    }

    public void setF(Integer f) {
        this.f = f;
    }

    public Integer getG() {
        return g;
    }

    public void setG(Integer g) {
        this.g = g;
    }

    public Integer getH() {
        return h;
    }

    public void setH(Integer h) {
        this.h = h;
    }

    public Integer getJ() {
        return j;
    }

    public void setJ(Integer j) {
        this.j = j;
    }

    public Integer getI() {
        return i;
    }

    public void setI(Integer i) {
        this.i = i;
    }

    public Integer getK() {
        return k;
    }

    public void setK(Integer k) {
        this.k = k;
    }


	public static Builder builder() {
		return new Builder();
	}
	
	public static Builder builder(AbcdefEntity abcdefEntity) {
		return new Builder(abcdefEntity);
	}

	public static class Builder {

    	private AbcdefEntity abcdefEntity;
    	
    	public Builder(){
    		this.abcdefEntity = new AbcdefEntity();
    	}
    	
    	public Builder(AbcdefEntity abcdefEntity){
    		this.abcdefEntity = abcdefEntity;
    	}
    	
    	public Builder id(Long id) {
    		abcdefEntity.setId(id);
        	return this;
    	}

    	public Builder a(Integer a) {
    		abcdefEntity.setA(a);
        	return this;
    	}

    	public Builder b(Integer b) {
    		abcdefEntity.setB(b);
        	return this;
    	}

    	public Builder c(Integer c) {
    		abcdefEntity.setC(c);
        	return this;
    	}

    	public Builder d(Integer d) {
    		abcdefEntity.setD(d);
        	return this;
    	}

    	public Builder e(Integer e) {
    		abcdefEntity.setE(e);
        	return this;
    	}

    	public Builder f(Integer f) {
    		abcdefEntity.setF(f);
        	return this;
    	}

    	public Builder g(Integer g) {
    		abcdefEntity.setG(g);
        	return this;
    	}

    	public Builder h(Integer h) {
    		abcdefEntity.setH(h);
        	return this;
    	}

    	public Builder j(Integer j) {
    		abcdefEntity.setJ(j);
        	return this;
    	}

    	public Builder i(Integer i) {
    		abcdefEntity.setI(i);
        	return this;
    	}

    	public Builder k(Integer k) {
    		abcdefEntity.setK(k);
        	return this;
    	}

		public AbcdefEntity build(){
			return abcdefEntity;
		}
	}

}