package de.greenrobot.daotest;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table AUTOINCREMENT_ENTITY.
 */
public class AutoincrementEntity {

    private Long id;

    public AutoincrementEntity() {
    }

    public AutoincrementEntity(Long id) {
        this.id = id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

}
