package de.greenrobot.daotest;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CHILDCLASS_ENTITY.
 */
public class ChildclassEntity {

    private Long id;
    private String text;

    public ChildclassEntity() {
    }

    public ChildclassEntity(Long id) {
        this.id = id;
    }

    public ChildclassEntity(Long id, String text) {
        this.id = id;
        this.text = text;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

}
