package de.greenrobot.daotest;

import de.greenrobot.daotest.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table RELATION_ENTITY.
 */
public class RelationEntity {

    private Long id;
    private Long parentId;
    private Long testId;
    private long testIdNotNull;
    private String simpleString;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient RelationEntityDao myDao;

    private RelationEntity parent;
    private Long parent__resolvedKey;

    private TestEntity testEntity;
    private Long testEntity__resolvedKey;

    private TestEntity testNotNull;
    private Long testNotNull__resolvedKey;

    private TestEntity testWithoutProperty;
    private boolean testWithoutProperty__refreshed;


    public RelationEntity() {
    }

    public RelationEntity(Long id) {
        this.id = id;
    }

    public RelationEntity(Long id, Long parentId, Long testId, long testIdNotNull, String simpleString) {
        this.id = id;
        this.parentId = parentId;
        this.testId = testId;
        this.testIdNotNull = testIdNotNull;
        this.simpleString = simpleString;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getRelationEntityDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getParentId() {
        return parentId;
    }

    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    public Long getTestId() {
        return testId;
    }

    public void setTestId(Long testId) {
        this.testId = testId;
    }

    public long getTestIdNotNull() {
        return testIdNotNull;
    }

    public void setTestIdNotNull(long testIdNotNull) {
        this.testIdNotNull = testIdNotNull;
    }

    public String getSimpleString() {
        return simpleString;
    }

    public void setSimpleString(String simpleString) {
        this.simpleString = simpleString;
    }

    /** To-one relationship, resolved on first access. */
    public RelationEntity getParent() {
        if (parent__resolvedKey == null || !parent__resolvedKey.equals(parentId)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            RelationEntityDao targetDao = daoSession.getRelationEntityDao();
            parent = targetDao.load(parentId);
            parent__resolvedKey = parentId;
        }
        return parent;
    }

    public void setParent(RelationEntity parent) {
        this.parent = parent;
        parentId = parent == null ? null : parent.getId();
        parent__resolvedKey = parentId;
    }

    /** To-one relationship, resolved on first access. */
    public TestEntity getTestEntity() {
        if (testEntity__resolvedKey == null || !testEntity__resolvedKey.equals(testId)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            TestEntityDao targetDao = daoSession.getTestEntityDao();
            testEntity = targetDao.load(testId);
            testEntity__resolvedKey = testId;
        }
        return testEntity;
    }

    public void setTestEntity(TestEntity testEntity) {
        this.testEntity = testEntity;
        testId = testEntity == null ? null : testEntity.getId();
        testEntity__resolvedKey = testId;
    }

    /** To-one relationship, resolved on first access. */
    public TestEntity getTestNotNull() {
        if (testNotNull__resolvedKey == null || !testNotNull__resolvedKey.equals(testIdNotNull)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            TestEntityDao targetDao = daoSession.getTestEntityDao();
            testNotNull = targetDao.load(testIdNotNull);
            testNotNull__resolvedKey = testIdNotNull;
        }
        return testNotNull;
    }

    public void setTestNotNull(TestEntity testNotNull) {
        if (testNotNull == null) {
            throw new DaoException("To-one property 'testIdNotNull' has not-null constraint; cannot set to-one to null");
        }
        this.testNotNull = testNotNull;
        testIdNotNull = testNotNull.getId();
        testNotNull__resolvedKey = testIdNotNull;
    }

    /** To-one relationship, resolved on first access. */
    public TestEntity getTestWithoutProperty() {
        if (testWithoutProperty != null || !testWithoutProperty__refreshed) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            TestEntityDao targetDao = daoSession.getTestEntityDao();
            targetDao.refresh(testWithoutProperty);
            testWithoutProperty__refreshed = true;
        }
        return testWithoutProperty;
    }

    /** To-one relationship, returned entity is not refreshed and may carry only the PK property. */
    public TestEntity peakTestWithoutProperty() {
        return testWithoutProperty;
    }

    public void setTestWithoutProperty(TestEntity testWithoutProperty) {
        this.testWithoutProperty = testWithoutProperty;
        testWithoutProperty__refreshed = true;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }


	public static Builder builder() {
		return new Builder();
	}
	
	public static Builder builder(RelationEntity relationEntity) {
		return new Builder(relationEntity);
	}

	public static class Builder {

    	private RelationEntity relationEntity;
    	
    	public Builder(){
    		this.relationEntity = new RelationEntity();
    	}
    	
    	public Builder(RelationEntity relationEntity){
    		this.relationEntity = relationEntity;
    	}
    	
    	public Builder id(Long id) {
    		relationEntity.setId(id);
        	return this;
    	}

    	public Builder parentId(Long parentId) {
    		relationEntity.setParentId(parentId);
        	return this;
    	}

    	public Builder testId(Long testId) {
    		relationEntity.setTestId(testId);
        	return this;
    	}

    	public Builder testIdNotNull(long testIdNotNull) {
    		relationEntity.setTestIdNotNull(testIdNotNull);
        	return this;
    	}

    	public Builder simpleString(String simpleString) {
    		relationEntity.setSimpleString(simpleString);
        	return this;
    	}

		public RelationEntity build(){
			return relationEntity;
		}
	}

}