package de.greenrobot.daotest;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SAVE_ENTITY.
 */
public class SaveEntity {

    private Long id;
    private String text;

    public SaveEntity() {
    }

    public SaveEntity(Long id) {
        this.id = id;
    }

    public SaveEntity(Long id, String text) {
        this.id = id;
        this.text = text;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

}
