package de.greenrobot.daotest;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SIMPLE_ENTITY.
 */
public class SimpleEntity {

    private Long id;
    private Boolean simpleBoolean;
    private Byte simpleByte;
    private Short simpleShort;
    private Integer simpleInt;
    private Long simpleLong;
    private Float simpleFloat;
    private Double simpleDouble;
    private String simpleString;
    private byte[] simpleByteArray;

    public SimpleEntity() {
    }

    public SimpleEntity(Long id) {
        this.id = id;
    }

    public SimpleEntity(Long id, Boolean simpleBoolean, Byte simpleByte, Short simpleShort, Integer simpleInt, Long simpleLong, Float simpleFloat, Double simpleDouble, String simpleString, byte[] simpleByteArray) {
        this.id = id;
        this.simpleBoolean = simpleBoolean;
        this.simpleByte = simpleByte;
        this.simpleShort = simpleShort;
        this.simpleInt = simpleInt;
        this.simpleLong = simpleLong;
        this.simpleFloat = simpleFloat;
        this.simpleDouble = simpleDouble;
        this.simpleString = simpleString;
        this.simpleByteArray = simpleByteArray;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Boolean getSimpleBoolean() {
        return simpleBoolean;
    }

    public void setSimpleBoolean(Boolean simpleBoolean) {
        this.simpleBoolean = simpleBoolean;
    }

    public Byte getSimpleByte() {
        return simpleByte;
    }

    public void setSimpleByte(Byte simpleByte) {
        this.simpleByte = simpleByte;
    }

    public Short getSimpleShort() {
        return simpleShort;
    }

    public void setSimpleShort(Short simpleShort) {
        this.simpleShort = simpleShort;
    }

    public Integer getSimpleInt() {
        return simpleInt;
    }

    public void setSimpleInt(Integer simpleInt) {
        this.simpleInt = simpleInt;
    }

    public Long getSimpleLong() {
        return simpleLong;
    }

    public void setSimpleLong(Long simpleLong) {
        this.simpleLong = simpleLong;
    }

    public Float getSimpleFloat() {
        return simpleFloat;
    }

    public void setSimpleFloat(Float simpleFloat) {
        this.simpleFloat = simpleFloat;
    }

    public Double getSimpleDouble() {
        return simpleDouble;
    }

    public void setSimpleDouble(Double simpleDouble) {
        this.simpleDouble = simpleDouble;
    }

    public String getSimpleString() {
        return simpleString;
    }

    public void setSimpleString(String simpleString) {
        this.simpleString = simpleString;
    }

    public byte[] getSimpleByteArray() {
        return simpleByteArray;
    }

    public void setSimpleByteArray(byte[] simpleByteArray) {
        this.simpleByteArray = simpleByteArray;
    }


	public static Builder builder() {
		return new Builder();
	}
	
	public static Builder builder(SimpleEntity simpleEntity) {
		return new Builder(simpleEntity);
	}

	public static class Builder {

    	private SimpleEntity simpleEntity;
    	
    	public Builder(){
    		this.simpleEntity = new SimpleEntity();
    	}
    	
    	public Builder(SimpleEntity simpleEntity){
    		this.simpleEntity = simpleEntity;
    	}
    	
    	public Builder id(Long id) {
    		simpleEntity.setId(id);
        	return this;
    	}

    	public Builder simpleBoolean(Boolean simpleBoolean) {
    		simpleEntity.setSimpleBoolean(simpleBoolean);
        	return this;
    	}

    	public Builder simpleByte(Byte simpleByte) {
    		simpleEntity.setSimpleByte(simpleByte);
        	return this;
    	}

    	public Builder simpleShort(Short simpleShort) {
    		simpleEntity.setSimpleShort(simpleShort);
        	return this;
    	}

    	public Builder simpleInt(Integer simpleInt) {
    		simpleEntity.setSimpleInt(simpleInt);
        	return this;
    	}

    	public Builder simpleLong(Long simpleLong) {
    		simpleEntity.setSimpleLong(simpleLong);
        	return this;
    	}

    	public Builder simpleFloat(Float simpleFloat) {
    		simpleEntity.setSimpleFloat(simpleFloat);
        	return this;
    	}

    	public Builder simpleDouble(Double simpleDouble) {
    		simpleEntity.setSimpleDouble(simpleDouble);
        	return this;
    	}

    	public Builder simpleString(String simpleString) {
    		simpleEntity.setSimpleString(simpleString);
        	return this;
    	}

    	public Builder simpleByteArray(byte[] simpleByteArray) {
    		simpleEntity.setSimpleByteArray(simpleByteArray);
        	return this;
    	}

		public SimpleEntity build(){
			return simpleEntity;
		}
	}

}