package de.greenrobot.daotest;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SIMPLE_ENTITY_DEFAULT_VALUES.
 */
public class SimpleEntityDefaultValues {

    private static Boolean defaultSimpleBooleanTrue = true;
    private static boolean defaultSimpleBooleanFalse = false;
    private static Byte defaultSimpleByteMax = new Byte("127");
    private static byte defaultSimpleByteMin = new Byte("-128");
    private static Short defaultSimpleShortMax = new Short("32767");
    private static short defaultSimpleShortMin = new Short("-32768");
    private static Integer defaultSimpleIntMax = new Integer("2147483647");
    private static int defaultSimpleIntMin = new Integer("-2147483648");
    private static Long defaultSimpleLongMax = new Long("9223372036854775807");
    private static long defaultSimpleLongMin = new Long("-9223372036854775808");
    private static Float defaultSimpleFloatMax = new Float("3.4028235E38");
    private static float defaultSimpleFloatMin = new Float("1.4E-45");
    private static Double defaultSimpleDoubleMax = new Double("1.7976931348623157E308");
    private static double defaultSimpleDoubleMin = new Double("4.9E-324");
    private static String defaultSimpleString = "greenrobot greenDAO";
    private static String defaultSimpleStringNotNull = "greenrobot greenDAO";
    private static java.util.Date defaultSimpleDate = new java.util.Date(1381453387221L);
    private static java.util.Date defaultSimpleDateNotNull = new java.util.Date(1381453387229L);
    private long id;
    private Boolean simpleBooleanTrue;
    private boolean simpleBooleanFalse;
    private Byte simpleByteMax;
    private byte simpleByteMin;
    private Short simpleShortMax;
    private short simpleShortMin;
    private Integer simpleIntMax;
    private int simpleIntMin;
    private Long simpleLongMax;
    private long simpleLongMin;
    private Float simpleFloatMax;
    private float simpleFloatMin;
    private Double simpleDoubleMax;
    private double simpleDoubleMin;
    private String simpleString;
    /** Not-null value. */
    private String simpleStringNotNull;
    private java.util.Date simpleDate;
    /** Not-null value. */
    private java.util.Date simpleDateNotNull;

    public SimpleEntityDefaultValues() {
    }

    public SimpleEntityDefaultValues(long id) {
        this.id = id;
        this.simpleBooleanTrue = defaultSimpleBooleanTrue;
        this.simpleBooleanFalse = defaultSimpleBooleanFalse;
        this.simpleByteMax = defaultSimpleByteMax;
        this.simpleByteMin = defaultSimpleByteMin;
        this.simpleShortMax = defaultSimpleShortMax;
        this.simpleShortMin = defaultSimpleShortMin;
        this.simpleIntMax = defaultSimpleIntMax;
        this.simpleIntMin = defaultSimpleIntMin;
        this.simpleLongMax = defaultSimpleLongMax;
        this.simpleLongMin = defaultSimpleLongMin;
        this.simpleFloatMax = defaultSimpleFloatMax;
        this.simpleFloatMin = defaultSimpleFloatMin;
        this.simpleDoubleMax = defaultSimpleDoubleMax;
        this.simpleDoubleMin = defaultSimpleDoubleMin;
        this.simpleString = defaultSimpleString;
        this.simpleStringNotNull = defaultSimpleStringNotNull;
        this.simpleDate = defaultSimpleDate;
        this.simpleDateNotNull = defaultSimpleDateNotNull;
    }

    public SimpleEntityDefaultValues(long id, Boolean simpleBooleanTrue, boolean simpleBooleanFalse, Byte simpleByteMax, byte simpleByteMin, Short simpleShortMax, short simpleShortMin, Integer simpleIntMax, int simpleIntMin, Long simpleLongMax, long simpleLongMin, Float simpleFloatMax, float simpleFloatMin, Double simpleDoubleMax, double simpleDoubleMin, String simpleString, String simpleStringNotNull, java.util.Date simpleDate, java.util.Date simpleDateNotNull) {
        this.id = id;
        this.simpleBooleanTrue = simpleBooleanTrue == null ? SimpleEntityDefaultValues.defaultSimpleBooleanTrue : simpleBooleanTrue;
        this.simpleBooleanFalse = simpleBooleanFalse;
        this.simpleByteMax = simpleByteMax == null ? SimpleEntityDefaultValues.defaultSimpleByteMax : simpleByteMax;
        this.simpleByteMin = simpleByteMin;
        this.simpleShortMax = simpleShortMax == null ? SimpleEntityDefaultValues.defaultSimpleShortMax : simpleShortMax;
        this.simpleShortMin = simpleShortMin;
        this.simpleIntMax = simpleIntMax == null ? SimpleEntityDefaultValues.defaultSimpleIntMax : simpleIntMax;
        this.simpleIntMin = simpleIntMin;
        this.simpleLongMax = simpleLongMax == null ? SimpleEntityDefaultValues.defaultSimpleLongMax : simpleLongMax;
        this.simpleLongMin = simpleLongMin;
        this.simpleFloatMax = simpleFloatMax == null ? SimpleEntityDefaultValues.defaultSimpleFloatMax : simpleFloatMax;
        this.simpleFloatMin = simpleFloatMin;
        this.simpleDoubleMax = simpleDoubleMax == null ? SimpleEntityDefaultValues.defaultSimpleDoubleMax : simpleDoubleMax;
        this.simpleDoubleMin = simpleDoubleMin;
        this.simpleString = simpleString;
        this.simpleStringNotNull = simpleStringNotNull == null ? SimpleEntityDefaultValues.defaultSimpleStringNotNull : simpleStringNotNull;
        this.simpleDate = simpleDate;
        this.simpleDateNotNull = simpleDateNotNull == null ? SimpleEntityDefaultValues.defaultSimpleDateNotNull : simpleDateNotNull;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public Boolean getSimpleBooleanTrue() {
        return simpleBooleanTrue;
    }

    /** Get default value for simpleBooleanTrue. */
    public static Boolean getDefaultSimpleBooleanTrue(){
        return defaultSimpleBooleanTrue;
    }
    public void setSimpleBooleanTrue(Boolean simpleBooleanTrue) {
        this.simpleBooleanTrue = simpleBooleanTrue;
    }

    public boolean getSimpleBooleanFalse() {
        return simpleBooleanFalse;
    }

    /** Get default value for simpleBooleanFalse. */
    public static boolean getDefaultSimpleBooleanFalse(){
        return defaultSimpleBooleanFalse;
    }
    public void setSimpleBooleanFalse(boolean simpleBooleanFalse) {
        this.simpleBooleanFalse = simpleBooleanFalse;
    }

    public Byte getSimpleByteMax() {
        return simpleByteMax;
    }

    /** Get default value for simpleByteMax. */
    public static Byte getDefaultSimpleByteMax(){
        return defaultSimpleByteMax;
    }
    public void setSimpleByteMax(Byte simpleByteMax) {
        this.simpleByteMax = simpleByteMax;
    }

    public byte getSimpleByteMin() {
        return simpleByteMin;
    }

    /** Get default value for simpleByteMin. */
    public static byte getDefaultSimpleByteMin(){
        return defaultSimpleByteMin;
    }
    public void setSimpleByteMin(byte simpleByteMin) {
        this.simpleByteMin = simpleByteMin;
    }

    public Short getSimpleShortMax() {
        return simpleShortMax;
    }

    /** Get default value for simpleShortMax. */
    public static Short getDefaultSimpleShortMax(){
        return defaultSimpleShortMax;
    }
    public void setSimpleShortMax(Short simpleShortMax) {
        this.simpleShortMax = simpleShortMax;
    }

    public short getSimpleShortMin() {
        return simpleShortMin;
    }

    /** Get default value for simpleShortMin. */
    public static short getDefaultSimpleShortMin(){
        return defaultSimpleShortMin;
    }
    public void setSimpleShortMin(short simpleShortMin) {
        this.simpleShortMin = simpleShortMin;
    }

    public Integer getSimpleIntMax() {
        return simpleIntMax;
    }

    /** Get default value for simpleIntMax. */
    public static Integer getDefaultSimpleIntMax(){
        return defaultSimpleIntMax;
    }
    public void setSimpleIntMax(Integer simpleIntMax) {
        this.simpleIntMax = simpleIntMax;
    }

    public int getSimpleIntMin() {
        return simpleIntMin;
    }

    /** Get default value for simpleIntMin. */
    public static int getDefaultSimpleIntMin(){
        return defaultSimpleIntMin;
    }
    public void setSimpleIntMin(int simpleIntMin) {
        this.simpleIntMin = simpleIntMin;
    }

    public Long getSimpleLongMax() {
        return simpleLongMax;
    }

    /** Get default value for simpleLongMax. */
    public static Long getDefaultSimpleLongMax(){
        return defaultSimpleLongMax;
    }
    public void setSimpleLongMax(Long simpleLongMax) {
        this.simpleLongMax = simpleLongMax;
    }

    public long getSimpleLongMin() {
        return simpleLongMin;
    }

    /** Get default value for simpleLongMin. */
    public static long getDefaultSimpleLongMin(){
        return defaultSimpleLongMin;
    }
    public void setSimpleLongMin(long simpleLongMin) {
        this.simpleLongMin = simpleLongMin;
    }

    public Float getSimpleFloatMax() {
        return simpleFloatMax;
    }

    /** Get default value for simpleFloatMax. */
    public static Float getDefaultSimpleFloatMax(){
        return defaultSimpleFloatMax;
    }
    public void setSimpleFloatMax(Float simpleFloatMax) {
        this.simpleFloatMax = simpleFloatMax;
    }

    public float getSimpleFloatMin() {
        return simpleFloatMin;
    }

    /** Get default value for simpleFloatMin. */
    public static float getDefaultSimpleFloatMin(){
        return defaultSimpleFloatMin;
    }
    public void setSimpleFloatMin(float simpleFloatMin) {
        this.simpleFloatMin = simpleFloatMin;
    }

    public Double getSimpleDoubleMax() {
        return simpleDoubleMax;
    }

    /** Get default value for simpleDoubleMax. */
    public static Double getDefaultSimpleDoubleMax(){
        return defaultSimpleDoubleMax;
    }
    public void setSimpleDoubleMax(Double simpleDoubleMax) {
        this.simpleDoubleMax = simpleDoubleMax;
    }

    public double getSimpleDoubleMin() {
        return simpleDoubleMin;
    }

    /** Get default value for simpleDoubleMin. */
    public static double getDefaultSimpleDoubleMin(){
        return defaultSimpleDoubleMin;
    }
    public void setSimpleDoubleMin(double simpleDoubleMin) {
        this.simpleDoubleMin = simpleDoubleMin;
    }

    public String getSimpleString() {
        return simpleString;
    }

    /** Get default value for simpleString. */
    public static String getDefaultSimpleString(){
        return defaultSimpleString;
    }
    public void setSimpleString(String simpleString) {
        this.simpleString = simpleString;
    }

    /** Not-null value. */
    public String getSimpleStringNotNull() {
        return simpleStringNotNull;
    }

    /** Get default value for simpleStringNotNull. */
    public static String getDefaultSimpleStringNotNull(){
        return defaultSimpleStringNotNull;
    }
    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSimpleStringNotNull(String simpleStringNotNull) {
        this.simpleStringNotNull = simpleStringNotNull;
    }

    public java.util.Date getSimpleDate() {
        return simpleDate;
    }

    /** Get default value for simpleDate. */
    public static java.util.Date getDefaultSimpleDate(){
        return defaultSimpleDate;
    }
    public void setSimpleDate(java.util.Date simpleDate) {
        this.simpleDate = simpleDate;
    }

    /** Not-null value. */
    public java.util.Date getSimpleDateNotNull() {
        return simpleDateNotNull;
    }

    /** Get default value for simpleDateNotNull. */
    public static java.util.Date getDefaultSimpleDateNotNull(){
        return defaultSimpleDateNotNull;
    }
    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSimpleDateNotNull(java.util.Date simpleDateNotNull) {
        this.simpleDateNotNull = simpleDateNotNull;
    }

}
