package de.greenrobot.daotest;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/**
 * Entity mapped to table SPECIAL_NAMES_ENTITY (schema version 1).
 */
public class SpecialNamesEntity {

    private Long id;
    private String count;
    private String select;
    private String sum;
    private String avg;
    private String join;
    private String distinct;
    private String on;
    private String index;

    public SpecialNamesEntity() {
    }

    public SpecialNamesEntity(Long id) {
        this.id = id;
    }

    public SpecialNamesEntity(Long id, String count, String select, String sum, String avg, String join, String distinct, String on, String index) {
        this.id = id;
        this.count = count;
        this.select = select;
        this.sum = sum;
        this.avg = avg;
        this.join = join;
        this.distinct = distinct;
        this.on = on;
        this.index = index;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCount() {
        return count;
    }

    public void setCount(String count) {
        this.count = count;
    }

    public String getSelect() {
        return select;
    }

    public void setSelect(String select) {
        this.select = select;
    }

    public String getSum() {
        return sum;
    }

    public void setSum(String sum) {
        this.sum = sum;
    }

    public String getAvg() {
        return avg;
    }

    public void setAvg(String avg) {
        this.avg = avg;
    }

    public String getJoin() {
        return join;
    }

    public void setJoin(String join) {
        this.join = join;
    }

    public String getDistinct() {
        return distinct;
    }

    public void setDistinct(String distinct) {
        this.distinct = distinct;
    }

    public String getOn() {
        return on;
    }

    public void setOn(String on) {
        this.on = on;
    }

    public String getIndex() {
        return index;
    }

    public void setIndex(String index) {
        this.index = index;
    }

}
