package de.greenrobot.daotest2.to1_specialentity;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table TO_ONE_TARGET2.
 */
public class ToOneTarget2 {

    private Long id;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public ToOneTarget2() {
    }

    public ToOneTarget2(Long id) {
        this.id = id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }


	public static Builder builder() {
		return new Builder();
	}
	
	public static Builder builder(ToOneTarget2 toOneTarget2) {
		return new Builder(toOneTarget2);
	}

	public static class Builder {

    	private ToOneTarget2 toOneTarget2;
    	
    	public Builder(){
    		this.toOneTarget2 = new ToOneTarget2();
    	}
    	
    	public Builder(ToOneTarget2 toOneTarget2){
    		this.toOneTarget2 = toOneTarget2;
    	}
    	
    	public Builder id(Long id) {
    		toOneTarget2.setId(id);
        	return this;
    	}

		public ToOneTarget2 build(){
			return toOneTarget2;
		}
	}

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}