package org.greenrobot.greendao.daotest;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "JOIN_MANY_TO_DATE_ENTITY".
 */
@Entity
public class JoinManyToDateEntity {

    @Id
    private Long id;
    private Long idToMany;
    private Long idDate;

    @Generated
    public JoinManyToDateEntity() {
    }

    public JoinManyToDateEntity(Long id) {
        this.id = id;
    }

    @Generated
    public JoinManyToDateEntity(Long id, Long idToMany, Long idDate) {
        this.id = id;
        this.idToMany = idToMany;
        this.idDate = idDate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getIdToMany() {
        return idToMany;
    }

    public void setIdToMany(Long idToMany) {
        this.idToMany = idToMany;
    }

    public Long getIdDate() {
        return idDate;
    }

    public void setIdDate(Long idDate) {
        this.idDate = idDate;
    }

}
