package org.greenrobot.greendao.daotest;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "STRING_KEY_VALUE_ENTITY".
 */
@Entity
public class StringKeyValueEntity {

    @Id
    private String key;
    private String value;

    @Generated
    public StringKeyValueEntity() {
    }

    public StringKeyValueEntity(String key) {
        this.key = key;
    }

    @Generated
    public StringKeyValueEntity(String key, String value) {
        this.key = key;
        this.value = value;
    }

    public String getKey() {
        return key;
    }

    public void setKey(String key) {
        this.key = key;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }

}
