package de.greenrobot.daotest2;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import android.os.Build;
// KEEP INCLUDES END
/**
 * Entity mapped to table KEEP_ENTITY.
 */
public class KeepEntity {

    private Long id;

    // KEEP FIELDS - put your custom fields here
    String extra = Build.VERSION.SDK;
    // KEEP FIELDS END

    public KeepEntity() {
    }

    public KeepEntity(Long id) {
        this.id = id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }


	public static Builder builder() {
		return new Builder();
	}
	
	public static Builder builder(KeepEntity keepEntity) {
		return new Builder(keepEntity);
	}

	public static class Builder {

    	private KeepEntity keepEntity;
    	
    	public Builder(){
    		this.keepEntity = new KeepEntity();
    	}
    	
    	public Builder(KeepEntity keepEntity){
    		this.keepEntity = keepEntity;
    	}
    	
    	public Builder id(Long id) {
    		keepEntity.setId(id);
        	return this;
    	}

		public KeepEntity build(){
			return keepEntity;
		}
	}

    // KEEP METHODS - put your custom methods here
    @Override
    public String toString() {
        return "KeepEntity ID=42 (extra=" + extra + ")";
    }
    // KEEP METHODS END

}