package de.greenrobot.dao.test;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoSession;

import de.greenrobot.dao.test.SimpleEntityDao;
import de.greenrobot.dao.test.SimpleEntityNotNullDao;
import de.greenrobot.dao.test.TestEntityDao;
import de.greenrobot.dao.test.RelationEntityDao;
import de.greenrobot.dao.test.DateEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * A DAO session is the main class you will interact wirth.
*/
public class DaoSession extends AbstractDaoSession {

    private final SimpleEntityDao simpleEntityDao;
    private final SimpleEntityNotNullDao simpleEntityNotNullDao;
    private final TestEntityDao testEntityDao;
    private final RelationEntityDao relationEntityDao;
    private final DateEntityDao dateEntityDao;

    public DaoSession(SQLiteDatabase db) {
        super(db);

        simpleEntityDao = new SimpleEntityDao(db, null);
        simpleEntityNotNullDao = new SimpleEntityNotNullDao(db, null);
        testEntityDao = new TestEntityDao(db, null);
        relationEntityDao = new RelationEntityDao(db, this, null);
        dateEntityDao = new DateEntityDao(db, null);

        registerDao(SimpleEntity.class, simpleEntityDao);
        registerDao(SimpleEntityNotNull.class, simpleEntityNotNullDao);
        registerDao(TestEntity.class, testEntityDao);
        registerDao(RelationEntity.class, relationEntityDao);
        registerDao(DateEntity.class, dateEntityDao);
    }
    
    public SimpleEntityDao getSimpleEntityDao() {
        return simpleEntityDao;
    }

    public SimpleEntityNotNullDao getSimpleEntityNotNullDao() {
        return simpleEntityNotNullDao;
    }

    public TestEntityDao getTestEntityDao() {
        return testEntityDao;
    }

    public RelationEntityDao getRelationEntityDao() {
        return relationEntityDao;
    }

    public DateEntityDao getDateEntityDao() {
        return dateEntityDao;
    }

}
