CREATE TABLE MINIMAL_ENTITY (_id INTEGER PRIMARY KEY);
INSERT INTO MINIMAL_ENTITY VALUES (1);
INSERT INTO MINIMAL_ENTITY 
	VALUES (2);
INSERT INTO MINIMAL_ENTITY VALUES (3)   ;
INSERT INTO MINIMAL_ENTITY VALUES (4);  
INSERT INTO MINIMAL_ENTITY VALUES (5) ;  
