package de.greenrobot.daoexample;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table NOTE.
 */
public class Note {

    private Long id;
    /** Not-null value. */
    private String text;
    private String comment;
    private java.util.Date date;

    public Note() {
    }

    public Note(Long id) {
        this.id = id;
    }

    public Note(Long id, String text, String comment, java.util.Date date) {
        this.id = id;
        this.text = text;
        this.comment = comment;
        this.date = date;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getText() {
        return text;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setText(String text) {
        this.text = text;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }


	public static Builder builder() {
		return new Builder();
	}
	
	public static Builder builder(Note note) {
		return new Builder(note);
	}

	public static class Builder {

    	private Note note;
    	
    	public Builder(){
    		this.note = new Note();
    	}
    	
    	public Builder(Note note){
    		this.note = note;
    	}
    	
    	public Builder id(Long id) {
    		note.setId(id);
        	return this;
    	}

    	public Builder text(String text) {
    		note.setText(text);
        	return this;
    	}

    	public Builder comment(String comment) {
    		note.setComment(comment);
        	return this;
    	}

    	public Builder date(java.util.Date date) {
    		note.setDate(date);
        	return this;
    	}

		public Note build(){
			return note;
		}
	}

}