package de.greenrobot.daotest2.dao;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.IdentityScopeType;
import de.greenrobot.dao.wrapper.SQLiteDatabaseWrapper;
import de.greenrobot.dao.wrapper.SQLiteOpenHelperWrapper;
import de.greenrobot.daotest2.specialdao.RelationSource2Dao;
import de.greenrobot.daotest2.to1_specialdao.ToOneTarget2Dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 1): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 1;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabaseWrapper db, boolean ifNotExists) {
        KeepEntityDao.createTable(db, ifNotExists);
        ToManyTarget2Dao.createTable(db, ifNotExists);
        ToOneTarget2Dao.createTable(db, ifNotExists);
        RelationSource2Dao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabaseWrapper db, boolean ifExists) {
        KeepEntityDao.dropTable(db, ifExists);
        ToManyTarget2Dao.dropTable(db, ifExists);
        ToOneTarget2Dao.dropTable(db, ifExists);
        RelationSource2Dao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelperWrapper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, null, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabaseWrapper db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabaseWrapper db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabaseWrapper db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(KeepEntityDao.class);
        registerDaoClass(ToManyTarget2Dao.class);
        registerDaoClass(ToOneTarget2Dao.class);
        registerDaoClass(RelationSource2Dao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
