package org.greenrobot.greendao.daotest2;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import android.os.Build;
// KEEP INCLUDES END

/**
 * Entity mapped to table "KEEP_ENTITY".
 */
@Entity
public class KeepEntity {

    @Id
    private Long id;

    // KEEP FIELDS - put your custom fields here
    String extra = Build.VERSION.SDK;
    // KEEP FIELDS END

    @Generated
    public KeepEntity() {
    }

    @Generated
    public KeepEntity(Long id) {
        this.id = id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    // KEEP METHODS - put your custom methods here
    @Override
    public String toString() {
        return "KeepEntity ID=42 (extra=" + extra + ")";
    }
    // KEEP METHODS END

}
