package org.greenrobot.greendao.daotest2;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "TO_MANY_TARGET2".
 */
@Entity
public class ToManyTarget2 {

    @Id
    private Long id;
    private Long fkId;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public ToManyTarget2() {
    }

    public ToManyTarget2(Long id) {
        this.id = id;
    }

    @Generated
    public ToManyTarget2(Long id, Long fkId) {
        this.id = id;
        this.fkId = fkId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getFkId() {
        return fkId;
    }

    public void setFkId(Long fkId) {
        this.fkId = fkId;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
