package de.greenrobot.dao.unittest;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "MINIMAL_ENTITY".
 */
public class MinimalEntity {

    private Long id;

    public MinimalEntity() {
    }

    public MinimalEntity(Long id) {
        this.id = id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

}
